import { runStructuredModel, StructuredModelError } from "../ollama";
import { LEGAL_ADVISOR_SYSTEM_PROMPT, wrapAgentInput } from "./prompts";
import { legalAdvisorySchema, validateLegalAdvisory } from "./paid-schemas";
import { ensureUsefulAdvisory } from "./legal-fallback";
import type { LegalConsultationEnvelope } from "./types";
import type { LegalModelContext } from "../payments/types";
export { buildLegalModelContext, fingerprintObject } from "./legal-context";

export async function runLegalAdvisor(args:{operationId:string;context:LegalModelContext;absoluteDeadline:number;attemptGrant:number;signal?:AbortSignal}):Promise<LegalConsultationEnvelope>{let lastReason="invalid legal advisory";for(let attempt=0;attempt<Math.min(2,args.attemptGrant);attempt++){const remaining=args.absoluteDeadline-Date.now();if(remaining<=0)throw new Error("workflow_deadline");try{const prompt=attempt===0?wrapAgentInput(args.context):`${wrapAgentInput(args.context)}\n\n<SERVER_REPAIR_INSTRUCTION>Return only a corrected LegalAdvisory schema object. Validation issue: ${lastReason}</SERVER_REPAIR_INSTRUCTION>`;const result=await runStructuredModel({systemPrompt:LEGAL_ADVISOR_SYSTEM_PROMPT,prompt,schema:legalAdvisorySchema,validator:(v)=>{const r=validateLegalAdvisory(v);if(r.ok===false){lastReason=r.reason;return null;}return r.value;},signal:args.signal,timeoutMs:Math.min(120_000,Math.max(1,remaining)),maxOutputTokens:650});return{operation_id:args.operationId,policy_version:"pegas-demo-legal-v1",advisory:ensureUsefulAdvisory(result.value,args.context),disclaimer:"Demo policy assessment. Not legal advice or approval to sign."};}catch(error){if(error instanceof StructuredModelError&&error.code==="INVALID_OUTPUT"&&attempt+1<Math.min(2,args.attemptGrant))continue;throw error;}}throw new Error("invalid_legal_output");}
