import type { LegalAdvisory, PaidDepartment, PaidReviewDecision, PaidRoutingDecision, Priority, Confidentiality } from "./types";
import type { ValidationResult } from "./schemas";

const paidDepartments=["technical","business","finance","legal"] as const;
const priorities=["low","medium","high"] as const;
const confidentiality=["internal","confidential","restricted"] as const;
const reviewDecisions=["approved","revise","manual_review","needs_information"] as const;
function record(v:unknown):v is Record<string,unknown>{return typeof v==="object"&&v!==null&&!Array.isArray(v)}
function text(v:unknown,name:string,max:number,optional=false):ValidationResult<string>{if(v===undefined&&optional)return{ok:true,value:"",normalized_fields:[`defaulted_${name}`]};if(typeof v!=="string")return{ok:false,reason:`${name} must be a string`};const s=v.trim();if(!optional&&!s)return{ok:false,reason:`${name} must not be empty`};if(s.length>max)return{ok:false,reason:`${name} exceeds ${max} chars`};return{ok:true,value:s,normalized_fields:[]}}
function enumValue<T extends readonly string[]>(v:unknown,name:string,values:T):ValidationResult<T[number]>{if(typeof v!=="string")return{ok:false,reason:`${name} must be a string`};const s=v.trim().toLowerCase();if(!values.includes(s as T[number]))return{ok:false,reason:`${name} unsupported`};return{ok:true,value:s as T[number],normalized_fields:s===v?[]:[`normalized_${name}`]}}
function arr(v:unknown,name:string,max=4,len=240):ValidationResult<string[]>{if(v===undefined)return{ok:true,value:[],normalized_fields:[`defaulted_${name}`]};if(!Array.isArray(v))return{ok:false,reason:`${name} must be an array`};if(v.length>max)return{ok:false,reason:`${name} exceeds ${max} entries`};const out:string[]=[];for(const x of v){const t=text(x,name,len);if(t.ok===false)return{ok:false,reason:t.reason};out.push(t.value)}return{ok:true,value:out,normalized_fields:[]}}
function exactEvidence(v:unknown,source:string):ValidationResult<string[]>{const a=arr(v,"evidence",3,240);if(a.ok===false)return{ok:false,reason:a.reason};for(const item of a.value)if(!source.includes(item))return{ok:false,reason:"evidence must be an exact substring of allowed context"};return a}

export const paidRoutingSchema={type:"object",properties:{department:{type:"string",enum:paidDepartments},summary:{type:"string"},priority:{type:"string",enum:priorities},confidentiality:{type:"string",enum:confidentiality},routing_reason:{type:"string"},department_brief:{type:"string"},next_action:{type:"string"},open_questions:{type:"array",items:{type:"string"},maxItems:4},evidence:{type:"array",items:{type:"string"},maxItems:3},consultation_request:{anyOf:[{type:"null"},{type:"object",properties:{service_id:{type:"string",enum:["legal_consultation"]},question:{type:"string"},reason:{type:"string"}},required:["service_id","question","reason"]}]}},required:["department","summary","priority","confidentiality","routing_reason","department_brief","next_action","consultation_request"]} as const;
export function validatePaidRouting(v:unknown,source:string):ValidationResult<PaidRoutingDecision>{
 if(!record(v))return{ok:false,reason:"paid routing output must be an object"};
 const dep=enumValue(v.department,"department",paidDepartments);if(dep.ok===false)return{ok:false,reason:dep.reason};
 const summary=text(v.summary,"summary",300);if(summary.ok===false)return{ok:false,reason:summary.reason};
 const priority=enumValue(v.priority,"priority",priorities);if(priority.ok===false)return{ok:false,reason:priority.reason};
 const conf=enumValue(v.confidentiality,"confidentiality",confidentiality);if(conf.ok===false)return{ok:false,reason:conf.reason};
 const rr=text(v.routing_reason,"routing_reason",240);if(rr.ok===false)return{ok:false,reason:rr.reason};
 const brief=text(v.department_brief,"department_brief",500);if(brief.ok===false)return{ok:false,reason:brief.reason};
 const next=text(v.next_action,"next_action",400);if(next.ok===false)return{ok:false,reason:next.reason};
 const oq=arr(v.open_questions,"open_questions",4,240);if(oq.ok===false)return{ok:false,reason:oq.reason};
 const ev=exactEvidence(v.evidence,source);if(ev.ok===false)return{ok:false,reason:ev.reason};
 let consultation:null|{service_id:"legal_consultation";question:string;reason:string}=null;
 if(v.consultation_request!==null&&v.consultation_request!==undefined){if(!record(v.consultation_request))return{ok:false,reason:"consultation_request must be object or null"};if(v.consultation_request.service_id!=="legal_consultation")return{ok:false,reason:"consultation_request.service_id must be legal_consultation"};const q=text(v.consultation_request.question,"consultation_request.question",500);if(q.ok===false)return{ok:false,reason:q.reason};const r=text(v.consultation_request.reason,"consultation_request.reason",300);if(r.ok===false)return{ok:false,reason:r.reason};consultation={service_id:"legal_consultation",question:q.value,reason:r.value};}
 if(dep.value==="legal"&&!consultation)return{ok:false,reason:"legal destination requires consultation_request"};if(dep.value!=="legal"&&consultation)return{ok:false,reason:"non-legal destination requires consultation_request=null"};
 return{ok:true,value:{department:dep.value as PaidDepartment,summary:summary.value,priority:priority.value as Priority,confidentiality:conf.value as Confidentiality,routing_reason:rr.value,department_brief:brief.value,next_action:next.value,open_questions:oq.value,evidence:ev.value,consultation_request:consultation},normalized_fields:[]};
}

export const paidReviewSchema={type:"object",properties:{decision:{type:"string",enum:reviewDecisions},issues:{type:"array",items:{type:"string"}},correction_target:{type:"string",enum:[...paidDepartments,""]},correction_request:{type:"string"},reason:{type:"string"},evidence:{type:"array",items:{type:"string"},maxItems:3}},required:["decision","reason"]} as const;
export function validatePaidReview(v:unknown,source:string):ValidationResult<PaidReviewDecision>{if(!record(v))return{ok:false,reason:"paid review output must be object"};const d=enumValue(v.decision,"decision",reviewDecisions);if(d.ok===false)return{ok:false,reason:d.reason};const issues=arr(v.issues,"issues",8,240);if(issues.ok===false)return{ok:false,reason:issues.reason};const reason=text(v.reason,"reason",240);if(reason.ok===false)return{ok:false,reason:reason.reason};const cr=text(v.correction_request,"correction_request",300,true);if(cr.ok===false)return{ok:false,reason:cr.reason};let target:PaidDepartment|null=null;if(v.correction_target){const t=enumValue(v.correction_target,"correction_target",paidDepartments);if(t.ok===false)return{ok:false,reason:t.reason};target=t.value;}const ev=exactEvidence(v.evidence,source);if(ev.ok===false)return{ok:false,reason:ev.reason};return{ok:true,value:{decision:d.value,issues:issues.value,correction_target:target,correction_request:cr.value||null,reason:reason.value,evidence:ev.value},normalized_fields:[]};}

export const legalAdvisorySchema={type:"object",properties:{verdict:{type:"string",enum:["no_policy_issue_identified","human_review_required","needs_information"]},summary:{type:"string"},findings:{type:"array",items:{type:"object",properties:{policy_id:{type:"string",enum:["DL-01","DL-02","DL-03"]},observation:{type:"string"},recommended_action:{type:"string"}},required:["policy_id","observation","recommended_action"]},maxItems:3},next_action:{type:"string"},open_questions:{type:"array",items:{type:"string"},maxItems:4}},required:["verdict","summary","findings","next_action","open_questions"]} as const;
export function validateLegalAdvisory(v:unknown):ValidationResult<LegalAdvisory>{if(!record(v))return{ok:false,reason:"legal advisory must be object"};const verdict=enumValue(v.verdict,"verdict",["no_policy_issue_identified","human_review_required","needs_information"] as const);if(verdict.ok===false)return{ok:false,reason:verdict.reason};const summary=text(v.summary,"summary",500);if(summary.ok===false)return{ok:false,reason:summary.reason};const next=text(v.next_action,"next_action",500);if(next.ok===false)return{ok:false,reason:next.reason};const oq=arr(v.open_questions,"open_questions",4,240);if(oq.ok===false)return{ok:false,reason:oq.reason};if(!Array.isArray(v.findings)||v.findings.length>3)return{ok:false,reason:"findings must contain <=3 items"};const findings:LegalAdvisory["findings"]=[];for(const f of v.findings){if(!record(f)||!(f.policy_id==="DL-01"||f.policy_id==="DL-02"||f.policy_id==="DL-03"))return{ok:false,reason:"invalid finding policy_id"};const o=text(f.observation,"observation",400);if(o.ok===false)return{ok:false,reason:o.reason};const a=text(f.recommended_action,"recommended_action",400);if(a.ok===false)return{ok:false,reason:a.reason};findings.push({policy_id:f.policy_id,observation:o.value,recommended_action:a.value});}const normalizedFields=[...verdict.normalized_fields];let normalizedVerdict=verdict.value;if(normalizedVerdict==="no_policy_issue_identified"&&findings.length>0){normalizedVerdict="human_review_required";normalizedFields.push("normalized_verdict_from_findings");}return{ok:true,value:{verdict:normalizedVerdict,summary:summary.value,findings,next_action:next.value,open_questions:oq.value},normalized_fields:normalizedFields};}
