import { runStructuredModel, StructuredModelError } from "../ollama";
import { createEventFactory, type EventEmitter } from "./events";
import { sanitizeRequest } from "./sanitize";
import { shouldRunPrivacy, privacyTerminalDecision } from "./privacy";
import { INTAKE_SYSTEM_PROMPT, PRIVACY_SYSTEM_PROMPT, PAID_ROUTING_SYSTEM_PROMPT, PAID_REVIEWER_SYSTEM_PROMPT, paidRoutingRevisionPrompt, wrapAgentInput } from "./prompts";
import { intakeSchema, privacySchema, validateIntake, validatePrivacy, type ValidationResult } from "./schemas";
import { paidRoutingSchema, paidReviewSchema, validatePaidRouting, validatePaidReview } from "./paid-schemas";
import { PAID_DEPARTMENT_PROFILES } from "./paid-departments";
import { decidePaidReviewPath } from "./paid-correction";
import type { AgentId, Confidentiality, FinalRequestCard, IntakeAssessment, LegalConsultationEnvelope, PaidDepartment, PaidRoutingDecision, PrivacyDecision, WorkflowEvent } from "./types";
import { validatePaymentConfig } from "../payments/config";
import { createAgentMandate } from "../payments/mandate";
import { resolveAgent, verifyRegistryBindings } from "../payments/agent-registry";
import { PaymentLedger, sha256 } from "../payments/store";
import { decodePaymentRequiredHeader, freezePaymentRequired, getFacilitatorSupport, quoteFingerprint, requireFrozenOffer } from "../payments/x402-server";
import { evaluateMandatePolicy } from "../payments/policy";
import { buildPublicEvidence } from "../payments/evidence";
import { buildLegalModelContext, fingerprintObject } from "./legal-context";
import { signInternalEnvelope } from "../payments/internal-auth";
import { paidFetchWithFrozenX402 } from "../payments/x402-client";
import type { PublicAgenticPaymentEvidence, X402PaymentRequired } from "../payments/types";

type PaidServiceResponse={error?:string;legal_ready?:boolean;evidence?:PublicAgenticPaymentEvidence;legal_consultation?:LegalConsultationEnvelope};

const MODEL_ATTEMPT_MS=120_000;const MAX_ATTEMPTS=14;const REPAIR="Your previous response failed the structured contract. Return only the corrected object with no extra keys.";
class PaidWorkflowError extends Error{constructor(public code:string,public detail:string|null=null){super(code)}}
function safeError(error:unknown){const code=error instanceof PaidWorkflowError?error.code:"model_error";const map:Record<string,string>={model_offline:"The model is currently unreachable.",model_timeout:"The model timed out.",invalid_model_output:"An agent response failed its structured contract after one repair.",workflow_deadline:"The paid workflow reached its execution deadline.",call_budget:"The paid workflow reached its model-call budget.",interrupted:"The workflow was interrupted.",payment_unavailable:"Agentic payment capability is unavailable.",payment_declined:"Deterministic payment authority declined the consultation.",payment_failed:"The payment could not be proven safely.",model_error:"The workflow could not complete safely."};return{code,message:map[code]??map.model_error,validation_detail:error instanceof PaidWorkflowError?error.detail:null};}
function evidenceSource(context:Record<string,unknown>){return typeof context.safe_brief==="string"?context.safe_brief:typeof context.sanitized_request==="string"?context.sanitized_request:"";}
function vague(message:string){const t=message.toLowerCase();return /\b(needs? help|an issue|some issue|a problem|some problem|please route|right team|who should handle|which team)\b/.test(t)&&!/\b(api|endpoint|integration|bug|technical|campaign|marketing|partnership|invoice|billing|payment|finance|refund|pricing|agreement|contract|nda|vendor|legal)\b/.test(t);}
function paidPrivacyContext(privacy:PrivacyDecision,intake:IntakeAssessment){return{safe_brief:privacy.safe_brief,request_type:intake.request_type,routing_hint:intake.department_candidate,priority:intake.priority,confidentiality:privacy.confidentiality,route_reason:intake.route_reason,privacy_reason:privacy.reason,recipient_restrictions:privacy.recipient_restrictions,evidence:privacy.evidence,department_profiles:PAID_DEPARTMENT_PROFILES};}
function card(args:{runId:string;routing?:PaidRoutingDecision|null;initial?:PaidDepartment|null;outcome:FinalRequestCard["outcome"];revision:0|1;reason:string;reviewStatus:string;question?:string|null;intake?:IntakeAssessment;confidentiality?:Confidentiality;evidence?:PublicAgenticPaymentEvidence|null;legal?:LegalConsultationEnvelope|null}):FinalRequestCard{const r=args.routing;const paid=r?.department??(args.intake?.department_candidate==="unknown"?null:args.intake?.department_candidate??null);const initial=args.initial??paid;return{run_id:args.runId,outcome:args.outcome,department:paid&&paid!=="legal"?paid:null,initial_department:initial&&initial!=="legal"?initial:null,revision_count:args.revision,priority:r?.priority??args.intake?.priority??null,confidentiality:args.confidentiality??r?.confidentiality??args.intake?.confidentiality??null,summary:r?.summary??args.intake?.summary??null,department_note:r?.department_brief??null,next_action:args.outcome==="needs_information"?null:r?.next_action??null,route_explanation:args.reason,review_status:args.reviewStatus,clarification_question:args.question??null,scenario:"paid_legal",paid_department:paid,initial_paid_department:initial,legal_consultation:args.legal??null,agentic_payment_evidence:args.evidence??null};}

export async function runPaidWorkflow(args:{rawMessage:string;runId:string;operationId:string;sessionScope:string;absoluteDeadline:number;emitExternal:EventEmitter;signal?:AbortSignal}){
 const factory=createEventFactory(args.runId);let attempts=0;const emit=(type:WorkflowEvent["type"],step:string,agent:AgentId|null,payload:unknown)=>{const event=factory(type,step,agent,payload);if(event)args.emitExternal(event)};const remaining=()=>args.absoluteDeadline-Date.now();const active=()=>{if(args.signal?.aborted)throw new PaidWorkflowError("interrupted");if(remaining()<=0)throw new PaidWorkflowError("workflow_deadline")};
 const handoff=(sourceStep:string,targetStep:string,sourceAgent:AgentId,targetAgent:AgentId,reason:string,forwarded:Record<string,unknown>,withheld:string[])=>emit("handoff_created",`handoff-${sourceStep}-${targetStep}`,sourceAgent,{handoff_id:crypto.randomUUID(),run_id:args.runId,source_step_id:sourceStep,target_step_id:targetStep,source_agent_id:sourceAgent,target_agent_id:targetAgent,reason,forwarded_context:forwarded,withheld_field_names:withheld,created_at:new Date().toISOString()});
 async function call<T>(p:{agentId:AgentId;system:string;context:Record<string,unknown>;schema:unknown;validator:(v:unknown)=>ValidationResult<T>}){let repair=false,last="invalid output";while(true){active();if(attempts>=MAX_ATTEMPTS)throw new PaidWorkflowError("call_budget");attempts++;try{const prompt=repair?`${wrapAgentInput(p.context)}\n\n<SERVER_REPAIR_INSTRUCTION>${REPAIR} ${last}</SERVER_REPAIR_INSTRUCTION>`:wrapAgentInput(p.context);return(await runStructuredModel({systemPrompt:p.system,prompt,schema:p.schema,validator:(v)=>{const r=p.validator(v);if(r.ok===false){last=r.reason;return null}return r.value},signal:args.signal,timeoutMs:Math.min(MODEL_ATTEMPT_MS,Math.max(1,remaining())),maxOutputTokens:650})).value}catch(error){if(error instanceof StructuredModelError&&error.code==="INVALID_OUTPUT"&&!repair){repair=true;continue}if(error instanceof StructuredModelError){if(error.code==="INVALID_OUTPUT")throw new PaidWorkflowError("invalid_model_output",`${p.agentId}: ${last}`);if(error.code==="MODEL_OFFLINE")throw new PaidWorkflowError("model_offline");if(error.code==="MODEL_TIMEOUT")throw new PaidWorkflowError("model_timeout");}throw error}}}
 async function callPrivacy(context:Record<string,unknown>,source:string){emit("agent_started","privacy","privacy_agent",{role:"Privacy"});try{const v=await call({agentId:"privacy_agent",system:PRIVACY_SYSTEM_PROMPT,context,schema:privacySchema,validator:(x)=>validatePrivacy(x,source)});emit("agent_completed","privacy","privacy_agent",v);return v}catch(e){emit("agent_failed","privacy","privacy_agent",safeError(e));throw e}}
 async function callRouting(context:Record<string,unknown>,pass:1|2){emit("agent_started","routing","routing_agent",{role:"Routing",pass,scenario:"paid_legal"});try{const v=await call({agentId:"routing_agent",system:pass===1?PAID_ROUTING_SYSTEM_PROMPT:paidRoutingRevisionPrompt(),context,schema:paidRoutingSchema,validator:(x)=>validatePaidRouting(x,evidenceSource(context))});emit("agent_completed","routing","routing_agent",{...v,pass});emit("routing_decision","routing","routing_agent",{decision:"route",department:v.department,reason:v.routing_reason,pass});return v}catch(e){emit("agent_failed","routing","routing_agent",safeError(e));throw e}}
 async function callReviewer(context:Record<string,unknown>,pass:1|2){emit("agent_started","reviewer","reviewer_agent",{role:"Reviewer",pass});try{const v=await call({agentId:"reviewer_agent",system:PAID_REVIEWER_SYSTEM_PROMPT,context,schema:paidReviewSchema,validator:(x)=>validatePaidReview(x,evidenceSource(context))});emit("review_completed","reviewer","reviewer_agent",{...v,pass});return v}catch(e){emit("agent_failed","reviewer","reviewer_agent",safeError(e));throw e}}

 async function purchase(routing:PaidRoutingDecision,routingBase:Record<string,unknown>,withheld:string[],privacyCleared:boolean){if(routing.department!=="legal"||!routing.consultation_request)return null;emit("consultation_requested","payment","routing_agent",{service_id:"legal_consultation",reason:routing.consultation_request.reason});const validation=validatePaymentConfig();if(!validation.ok){emit("payment_failed","payment",null,{reason:"payment_configuration_unavailable"});throw new PaidWorkflowError("payment_unavailable",validation.errors.join("; "))}const config=validation.config;const ledger=new PaymentLedger(config);const mandate=createAgentMandate({operationId:args.operationId,purpose:routing.consultation_request.reason,absoluteDeadline:args.absoluteDeadline,config});await ledger.attachMandate(args.operationId,mandate);emit("mandate_created","payment",null,{mandate_id:mandate.mandate_id,fingerprint_sha256:mandate.fingerprint_sha256,principal:mandate.principal,acting_agent:mandate.acting_agent,service_id:mandate.service_id,counterparty_agent_id:mandate.counterparty_agent_id,max_amount_atomic:mandate.max_amount_atomic,max_authorizations:1,network:mandate.network,asset_mint:mandate.asset_mint,expires_at:mandate.expires_at,state:mandate.state});const registry=verifyRegistryBindings(config);if(!registry.ok){emit("payment_declined","payment",null,{reason:"counterparty_registry_mismatch"});throw new PaidWorkflowError("payment_declined",registry.errors.join("; "))}emit("counterparty_verified","payment",null,{registry_label:"KYA-lite | Demo identity registry",buyer:registry.buyer,seller:registry.seller});
 const safeBrief=privacyCleared&&typeof routingBase.safe_brief==="string"?routingBase.safe_brief:`${routing.summary} ${routing.department_brief}`.trim();const restrictions=privacyCleared&&Array.isArray(routingBase.recipient_restrictions)?routingBase.recipient_restrictions.filter((x):x is string=>typeof x==="string"):[];const legalContext=buildLegalModelContext({safeBrief,question:routing.consultation_request.question,relevantEvidence:routing.evidence,confidentiality:routing.confidentiality,recipientRestrictions:restrictions});const legalFingerprint=fingerprintObject(legalContext);const requestFingerprint=sha256(JSON.stringify({operation_id:args.operationId,service_id:"legal_consultation",legal_context_fingerprint:legalFingerprint}));const payload={operation_id:args.operationId,run_id:args.runId,request_fingerprint:requestFingerprint,legal_context_fingerprint:legalFingerprint,legal_context:legalContext,absolute_deadline:args.absoluteDeadline,remaining_model_attempt_grant:2};const internalAuth=signInternalEnvelope({operation_id:args.operationId,run_id:args.runId,request_fingerprint:requestFingerprint,legal_context_fingerprint:legalFingerprint,remaining_model_attempt_grant:2,absolute_deadline:args.absoluteDeadline,exp:Math.min(args.absoluteDeadline,Date.now()+60_000)},config.legalServiceAuthSecret);const url=`${config.legalServiceBaseUrl.replace(/\/$/,"")}/api/paid-services/legal-consultation`;
 const support=await getFacilitatorSupport(config,remaining());if(!support.supported)throw new PaidWorkflowError("payment_unavailable",support.reason);const unpaid=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json","X-Pegas-Internal-Auth":internalAuth},body:JSON.stringify(payload),redirect:"error",cache:"no-store",signal:args.signal});if(unpaid.status!==402)throw new PaidWorkflowError("payment_failed",`seller returned ${unpaid.status} instead of 402`);const requiredHeader=unpaid.headers.get("PAYMENT-REQUIRED");if(!requiredHeader)throw new PaidWorkflowError("payment_failed","missing PAYMENT-REQUIRED");let required:X402PaymentRequired;try{required=freezePaymentRequired(await decodePaymentRequiredHeader(requiredHeader))}catch{throw new PaidWorkflowError("payment_failed","malformed PAYMENT-REQUIRED")};if(!requireFrozenOffer(required,config,url))throw new PaidWorkflowError("payment_declined","seller quote does not match the frozen offer");emit("payment_required","payment",null,{x402_version:2,scheme:"exact",network:required.accepts[0].network,asset:required.accepts[0].asset,amount_atomic:required.accepts[0].amount,pay_to:required.accepts[0].payTo,fee_payer:required.accepts[0].extra.feePayer,payment_flow:"upfront",quote_fingerprint:quoteFingerprint(required)});
 const op=await ledger.get(args.operationId);if(!op)throw new PaidWorkflowError("payment_failed","operation ledger disappeared");let decision=evaluateMandatePolicy({config,mandate,buyer:resolveAgent(config,"pegas:routing-agent:v1"),seller:resolveAgent(config,"pegas:legal-advisor:v1"),quote:required.accepts[0],resourceUrl:required.resource.url,expectedResourceUrl:url,recipientRestrictions:restrictions,authorizationCount:op.authorization_count,remainingMs:remaining(),budgetAvailable:true});if(decision.controls.slice(0,9).every(x=>x.passed)){const reserve=await ledger.reserveAuthorization({operationId:args.operationId,sessionScope:args.sessionScope,amount:"10000",day:new Date().toISOString().slice(0,10)});if(reserve!=="ok")decision=evaluateMandatePolicy({config,mandate,buyer:resolveAgent(config,"pegas:routing-agent:v1"),seller:resolveAgent(config,"pegas:legal-advisor:v1"),quote:required.accepts[0],resourceUrl:required.resource.url,expectedResourceUrl:url,recipientRestrictions:restrictions,authorizationCount:0,remainingMs:remaining(),budgetAvailable:false});}else decision={...decision,decision:"declined"};let publicEvidence=buildPublicEvidence({config,operationId:args.operationId,mandate,policy:decision,feePayer:typeof required.accepts[0].extra.feePayer==="string"?required.accepts[0].extra.feePayer:null});await ledger.savePolicy(args.operationId,decision,publicEvidence);emit("mandate_policy_checked","payment",null,decision);if(decision.decision!=="approved"){emit("payment_declined","payment",null,{reason:"deterministic_authority_check_declined",controls:decision.controls});throw new PaidWorkflowError("payment_declined")}
 if(attempts+2>MAX_ATTEMPTS)throw new PaidWorkflowError("call_budget");attempts+=2;let authorizedEmitted=false,settlingEmitted=false;let paidResponse:Response;try{const paid=await paidFetchWithFrozenX402({config,url,body:JSON.stringify(payload),internalAuth,frozenPaymentRequired:required,onAuthorizationCreated:()=>{if(!authorizedEmitted){authorizedEmitted=true;emit("payment_authorized","payment",null,{mandate_id:mandate.mandate_id,amount_atomic:"10000",note:"Signed payload is intentionally not exposed."})}},onSettling:()=>{if(!settlingEmitted){settlingEmitted=true;emit("payment_settling","payment",null,{protocol:"x402",flow:"upfront"})}}});paidResponse=paid.response}catch(error){const latest=await ledger.get(args.operationId).catch(()=>null);if(latest?.state==="outcome_unknown")emit("payment_outcome_unknown","payment",null,{reason:"transport outcome unknown; no re-sign permitted"});else emit("payment_failed","payment",null,{reason:error instanceof Error?error.message:"paid transport failed"});throw new PaidWorkflowError("payment_failed")}
 const settlementResult=await paidResponse.json().catch(()=>null) as PaidServiceResponse|null;if(settlementResult?.evidence?.settlement?.transaction_signature){emit("payment_settled","payment",null,{transaction_signature:settlementResult.evidence.settlement.transaction_signature,facilitator_fee_payer:settlementResult.evidence.settlement.facilitator_fee_payer});if(settlementResult.evidence.settlement.confirmation_status==="confirmed"||settlementResult.evidence.settlement.confirmation_status==="finalized"){publicEvidence=settlementResult.evidence;emit("payment_confirmed","payment",null,{transaction_signature:publicEvidence.settlement.transaction_signature,explorer_url:publicEvidence.settlement.explorer_url,status:publicEvidence.settlement.confirmation_status,transfer_matches_offer:publicEvidence.settlement.transfer_matches_offer});emit("mandate_consumed","payment",null,{mandate_id:mandate.mandate_id,state:"consumed"});}}
 if(paidResponse.status===202){emit("payment_confirmation_pending","payment",null,{transaction_signature:settlementResult?.evidence?.settlement?.transaction_signature??null});throw new PaidWorkflowError("payment_failed","settlement exists but independent confirmation is pending")}
 if(!paidResponse.ok)throw new PaidWorkflowError("payment_failed",settlementResult?.error??`seller returned ${paidResponse.status}`);if(!settlementResult?.legal_ready||!settlementResult?.evidence)throw new PaidWorkflowError("payment_failed","seller response omitted confirmed payment evidence");
 // The real Legal handoff is emitted only after matching chain evidence and mandate consumption.
 handoff("routing","legal","routing_agent","legal_advisor_agent","Confirmed x402 settlement consumed the mandate; deliver the paid Legal advisory.",legalContext,withheld);emit("agent_started","legal","legal_advisor_agent",{role:"Legal Advisor",paid:true});
 const deliveryAuth=signInternalEnvelope({operation_id:args.operationId,run_id:args.runId,request_fingerprint:requestFingerprint,legal_context_fingerprint:legalFingerprint,remaining_model_attempt_grant:2,absolute_deadline:args.absoluteDeadline,exp:Math.min(args.absoluteDeadline,Date.now()+60_000)},config.legalServiceAuthSecret);const delivery=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json","X-Pegas-Internal-Auth":deliveryAuth,"Cache-Control":"no-store"},body:JSON.stringify({...payload,delivery_only:true}),redirect:"error",cache:"no-store",signal:args.signal});const deliveryResult=await delivery.json().catch(()=>null) as PaidServiceResponse|null;
 if(!delivery.ok||!deliveryResult?.legal_consultation||!deliveryResult?.evidence){emit("agent_failed","legal","legal_advisor_agent",{code:"legal_consultation_failed"});emit("consultation_failed","legal","legal_advisor_agent",{payment_preserved:true,evidence:deliveryResult?.evidence??settlementResult.evidence});throw new PaidWorkflowError("payment_failed",deliveryResult?.error??"legal consultation failed after confirmed payment")}
 emit("agent_completed","legal","legal_advisor_agent",deliveryResult.legal_consultation.advisory);emit("consultation_completed","legal","legal_advisor_agent",{policy_version:deliveryResult.legal_consultation.policy_version,disclaimer:deliveryResult.legal_consultation.disclaimer});return{legal:deliveryResult.legal_consultation as LegalConsultationEnvelope,evidence:deliveryResult.evidence as PublicAgenticPaymentEvidence,fingerprint:legalFingerprint};
 }

 try{const sanitized=sanitizeRequest(args.rawMessage);emit("workflow_started","workflow",null,{status:"running",scenario:"paid_legal",operation_id:args.operationId});emit("input_checked","input",null,{character_count:sanitized.sanitized.length,sensitivity_flag_types:sanitized.flagTypes,deterministic_sensitivity_flags:sanitized.deterministicSensitivityFlags,confidentiality_floor:sanitized.confidentialityFloor});if(sanitized.flagTypes.length){const reason="Credential-like material was detected and redacted. Paid mode stops before any model or payment call.";emit("workflow_completed","workflow",null,card({runId:args.runId,outcome:"manual_review",revision:0,reason,reviewStatus:"manual_review",confidentiality:"restricted"}));return}
 emit("agent_started","intake","intake_agent",{role:"Intake"});const intakeContext={sanitized_request:sanitized.sanitized,confidentiality_floor:sanitized.confidentialityFloor,deterministic_sensitivity_flags:sanitized.deterministicSensitivityFlags};let intake: IntakeAssessment;try{intake=await call({agentId:"intake_agent",system:INTAKE_SYSTEM_PROMPT,context:intakeContext,schema:intakeSchema,validator:(v)=>validateIntake(v,sanitized.sanitized)})}catch(e){emit("agent_failed","intake","intake_agent",safeError(e));throw e}emit("agent_completed","intake","intake_agent",intake);if(intake.confidentiality==="restricted"){emit("workflow_completed","workflow",null,card({runId:args.runId,intake,outcome:"manual_review",revision:0,reason:"Intake classified the request as restricted.",reviewStatus:"manual_review"}));return}if(intake.department_candidate==="unknown"||intake.clarification_question||vague(sanitized.sanitized)){emit("workflow_completed","workflow",null,card({runId:args.runId,intake,outcome:"needs_information",revision:0,reason:"The request needs clarification before paid routing.",reviewStatus:"needs_information",question:intake.clarification_question??"What additional context is needed?"}));return}
 const privacyNeeded=shouldRunPrivacy({intake,deterministicSensitivityFlags:sanitized.deterministicSensitivityFlags,confidentialityFloor:sanitized.confidentialityFloor});let privacy:PrivacyDecision|null=null,privacyCleared=false;let routingBase:Record<string,unknown>;let withheld=["raw_request"];if(privacyNeeded){const ctx={sanitized_request:sanitized.sanitized,intake:{summary:intake.summary,request_type:intake.request_type,department_candidate:intake.department_candidate,priority:intake.priority,confidentiality:intake.confidentiality,privacy_review_needed:intake.privacy_review_needed,route_reason:intake.route_reason,evidence:intake.evidence,missing_information:intake.missing_information},deterministic_sensitivity_flags:sanitized.deterministicSensitivityFlags,confidentiality_floor:sanitized.confidentialityFloor};handoff("intake","privacy","intake_agent","privacy_agent","Privacy review is required before paid routing.",ctx,["raw_request"]);privacy=await callPrivacy(ctx,sanitized.sanitized);const pd=privacyTerminalDecision({privacy,confidentialityFloor:sanitized.confidentialityFloor});if(pd!=="continue"){emit("workflow_completed","workflow",null,card({runId:args.runId,intake,outcome:pd==="needs_information"?"needs_information":"manual_review",revision:0,reason:privacy.reason,reviewStatus:`${pd}_after_privacy`,question:privacy.clarification_question,confidentiality:privacy.confidentiality}));return}privacyCleared=true;routingBase=paidPrivacyContext(privacy,intake);withheld=[...new Set(["raw_request",...privacy.withheld_field_names,"sanitized_request"])];handoff("privacy","routing","privacy_agent","routing_agent",privacy.reason,routingBase,withheld)}else{emit("agent_skipped","privacy","privacy_agent",{reason:"Privacy review not needed."});routingBase={sanitized_request:sanitized.sanitized,intake,department_profiles:PAID_DEPARTMENT_PROFILES};handoff("intake","routing","intake_agent","routing_agent","Paid Routing owns the destination decision.",routingBase,["raw_request"])}
 let routing=await callRouting(routingBase,1);const initial=routing.department;if(privacyCleared?routing.confidentiality==="restricted":routing.confidentiality!=="internal"){emit("workflow_completed","workflow",null,card({runId:args.runId,routing,initial,outcome:"manual_review",revision:0,reason:"Routing output requires manual review under the active confidentiality policy.",reviewStatus:"manual_review"}));return}
 let consultation:Awaited<ReturnType<typeof purchase>>=null;if(routing.department==="legal")consultation=await purchase(routing,routingBase,withheld,privacyCleared);else emit("consultation_skipped","payment","routing_agent",{reason:"Paid Routing selected a non-Legal destination; no payment capability was invoked."});const reviewerBase=privacyCleared?{...routingBase}:{safe_brief:`${routing.summary} ${routing.department_brief}`.trim(),intake:{summary:intake.summary,request_type:intake.request_type,priority:intake.priority},department_profiles:PAID_DEPARTMENT_PROFILES};const reviewerContext1={...reviewerBase,routing_decision:routing,...(consultation?{legal_consultation:consultation.legal,agentic_payment_evidence:consultation.evidence}:{}),correction_cycle:0};handoff("routing","reviewer","routing_agent","reviewer_agent","Review the paid RoutingDecision and any actual validated Legal advisory.",reviewerContext1,withheld);const review1=await callReviewer(reviewerContext1,1);const d1=decidePaidReviewPath({review:review1,currentDepartment:routing.department,routing,correctionCycleUsed:false,privacyCleared});if(d1.action==="approve"){const final=card({runId:args.runId,routing,initial,outcome:"routed_demo",revision:0,reason:routing.routing_reason,reviewStatus:privacyCleared?"approved_after_privacy":"approved",evidence:consultation?.evidence,legal:consultation?.legal});emit("workflow_completed","workflow",null,final);await new PaymentLedger(validatePaymentConfig().config).saveWorkflowResult(args.operationId,final).catch(()=>undefined);return}if(d1.action==="needs_information"){const final=card({runId:args.runId,routing,initial,outcome:"needs_information",revision:0,reason:routing.routing_reason,reviewStatus:"needs_information",question:review1.correction_request??routing.open_questions[0],evidence:consultation?.evidence,legal:consultation?.legal});emit("workflow_completed","workflow",null,final);return}if(d1.action==="manual_review"){const final=card({runId:args.runId,routing,initial,outcome:"manual_review",revision:0,reason:d1.reason,reviewStatus:review1.decision,evidence:consultation?.evidence,legal:consultation?.legal});emit("workflow_completed","workflow",null,final);return}
 emit("revision_requested","correction","reviewer_agent",{cycle:1,mode:d1.suggested_department===routing.department?"same_department":"reroute_suggested",from_department:routing.department,target_department:d1.suggested_department,reason:review1.reason,issues:review1.issues});const correctionContext={...routingBase,previous_routing_decision:routing,reviewer_issues:review1.issues,reviewer_reason:review1.reason,correction_request:review1.correction_request,suggested_department:d1.suggested_department,correction_cycle:1,...(consultation?{existing_paid_consultation:{fingerprint:consultation.fingerprint,policy_version:"pegas-demo-legal-v1"}}:{})};emit("correction_started","correction","routing_agent",{cycle:1,from_department:routing.department,suggested_department:d1.suggested_department});handoff("reviewer","routing","reviewer_agent","routing_agent",review1.correction_request??review1.reason,correctionContext,withheld);const previous=routing;routing=await callRouting(correctionContext,2);emit("correction_completed","correction","routing_agent",{cycle:1,from_department:previous.department,department:routing.department,rerouted:previous.department!==routing.department});if(privacyCleared?routing.confidentiality==="restricted":routing.confidentiality!=="internal"){const final=card({runId:args.runId,routing,initial,outcome:"manual_review",revision:1,reason:"Corrected route requires manual review.",reviewStatus:"manual_review_after_correction",evidence:consultation?.evidence,legal:consultation?.legal});emit("workflow_completed","workflow",null,final);return}
 if(routing.department==="legal"){const candidateContext=buildLegalModelContext({safeBrief:privacyCleared&&typeof routingBase.safe_brief==="string"?routingBase.safe_brief:`${routing.summary} ${routing.department_brief}`,question:routing.consultation_request!.question,relevantEvidence:routing.evidence,confidentiality:routing.confidentiality,recipientRestrictions:privacyCleared&&Array.isArray(routingBase.recipient_restrictions)?routingBase.recipient_restrictions.filter((x):x is string=>typeof x==="string"):[]});const fp=fingerprintObject(candidateContext);if(consultation){if(fp!==consultation.fingerprint){const final=card({runId:args.runId,routing,initial,outcome:"manual_review",revision:1,reason:"Correction materially changed the specialist input after payment; a second purchase is forbidden.",reviewStatus:"manual_review_no_second_purchase",evidence:consultation.evidence,legal:consultation.legal});emit("workflow_completed","workflow",null,final);return}emit("consultation_reused","legal","legal_advisor_agent",{reason:"Corrected route uses the same safe brief, question, and policy version; no second payment."})}else consultation=await purchase(routing,routingBase,withheld,privacyCleared)}
 const reviewerContext2={...reviewerBase,routing_decision:routing,previous_routing_decision:previous,reviewer_1:review1,correction_cycle:1,...(routing.department==="legal"&&consultation?{legal_consultation:consultation.legal,agentic_payment_evidence:consultation.evidence}:{})};handoff("routing","reviewer","routing_agent","reviewer_agent","Review the corrected RoutingDecision. Reviewer pass 2 is terminal.",reviewerContext2,withheld);const review2=await callReviewer(reviewerContext2,2);const d2=decidePaidReviewPath({review:review2,currentDepartment:routing.department,routing,correctionCycleUsed:true,privacyCleared});let final:FinalRequestCard;if(d2.action==="approve")final=card({runId:args.runId,routing,initial,outcome:"routed_demo",revision:1,reason:initial===routing.department?"Reviewer requested one revision and the corrected package passed terminal review.":`Routing changed the destination from ${initial} to ${routing.department}; terminal review approved it.`,reviewStatus:initial===routing.department?"approved_after_revision":"approved_after_reroute",evidence:consultation?.evidence,legal:routing.department==="legal"?consultation?.legal:null});else if(d2.action==="needs_information")final=card({runId:args.runId,routing,initial,outcome:"needs_information",revision:1,reason:"Terminal review needs more information.",reviewStatus:"needs_information_after_correction",question:review2.correction_request??routing.open_questions[0],evidence:consultation?.evidence,legal:routing.department==="legal"?consultation?.legal:null});else final=card({runId:args.runId,routing,initial,outcome:"manual_review",revision:1,reason:d2.action==="manual_review"?d2.reason:"The single correction cycle was exhausted.",reviewStatus:"manual_review_after_correction",question:review2.correction_request,evidence:consultation?.evidence,legal:routing.department==="legal"?consultation?.legal:null});emit("workflow_completed","workflow",null,final);await new PaymentLedger(validatePaymentConfig().config).saveWorkflowResult(args.operationId,final).catch(()=>undefined);
 }catch(error){emit("workflow_failed","workflow",null,safeError(error))}
}
