import type { ReactNode } from "react";
import type { FinalRequestCard, WorkflowEvent } from "@/lib/workflow/types";
import type { PublicAgenticPaymentEvidence } from "@/lib/payments/types";
function eventPayload(events:WorkflowEvent[],type:WorkflowEvent["type"]){return [...events].reverse().find(e=>e.type===type)?.payload as Record<string,unknown>|undefined}
function short(v:string|undefined|null){return v?v.length>20?`${v.slice(0,10)}…${v.slice(-8)}`:v:"—"}
export function AgenticPaymentInspector({events,card}:{events:WorkflowEvent[];card:FinalRequestCard|null}) {
 const e=card?.agentic_payment_evidence as PublicAgenticPaymentEvidence|undefined; const mandate=eventPayload(events,"mandate_created"); const policy=eventPayload(events,"mandate_policy_checked");
 if(!e&&!mandate&&!policy)return null;
 return <section className="rounded-3xl border border-slate-200 bg-white p-5 card-shadow"><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-400">Agentic payment inspector</p><h2 className="mt-1 text-lg font-semibold text-slate-950">Reconstructable payment evidence</h2><div className="mt-5 grid gap-4 lg:grid-cols-2">
  <Panel title="MANDATE"><KV k="Mandate" v={short(e?.authority.mandate_id ?? String(mandate?.mandate_id??""))}/><KV k="Fingerprint" v={short(e?.authority.mandate_fingerprint_sha256 ?? String(mandate?.fingerprint_sha256??""))}/><KV k="Principal" v={e?.authority.principal_id??"pegas-request-desk"}/><KV k="Acting agent" v={e?.authority.acting_agent_id??"pegas:routing-agent:v1"}/><KV k="Service" v={e?.authority.service_id??"legal_consultation"}/><KV k="Limit" v={`${e?.authority.max_amount_atomic??"10000"} atomic · max 1`}/><KV k="State" v={e?.authority.state??String(mandate?.state??"active")}/></Panel>
  <Panel title="POLICY CHECK"><KV k="Decision" v={e?.policy.decision??String(policy?.decision??"—")}/>{e?.policy.controls?.map(c=><div key={c.id} className="mt-2 rounded-xl bg-slate-50 p-2 text-xs"><b>{c.id} {c.passed?"✓":"✕"}</b><span className="ml-2 text-slate-600">{c.public_reason}</span></div>)}</Panel>
  <Panel title="AGENT IDENTITY"><KV k="Registry" v={e?.identity.registry_label??"KYA-lite | Demo identity registry"}/><KV k="Buyer" v={e?.identity.buyer_agent_id??"pegas:routing-agent:v1"}/><KV k="Buyer wallet" v={short(e?.identity.buyer_address)}/><KV k="Seller" v={e?.identity.seller_agent_id??"pegas:legal-advisor:v1"}/><KV k="Seller wallet" v={short(e?.identity.seller_address)}/></Panel>
  <Panel title="SETTLEMENT"><KV k="Protocol" v="x402 v2 · exact · upfront"/><KV k="Network" v={e?.settlement.network_label??"Solana Devnet"}/><KV k="Amount" v="10000 atomic · 0.01 test USDC"/><KV k="Signature" v={short(e?.settlement.transaction_signature)}/><KV k="Evidence" v={e?.settlement.confirmation_status??"unavailable"}/>{e?.settlement.explorer_url&&<a className="mt-3 inline-flex text-xs font-bold text-[var(--pegas-blue-dark)] underline" href={e.settlement.explorer_url} target="_blank" rel="noreferrer">Open Solana Explorer ↗</a>}<KV k="Legal delivery" v={e?.consultation.delivery_status??"not_started"}/></Panel>
 </div></section>
}
function Panel({title,children}:{title:string;children:ReactNode}){return <div className="rounded-2xl border border-slate-200 p-4"><p className="text-[11px] font-bold tracking-[0.14em] text-slate-500">{title}</p><div className="mt-3">{children}</div></div>}
function KV({k,v}:{k:string;v:string}){return <div className="grid grid-cols-[120px_1fr] gap-3 py-1.5 text-xs"><span className="text-slate-400">{k}</span><span className="break-all font-medium text-slate-700">{v}</span></div>}
