"use client";
import type { Department } from "@/lib/workflow/types";
export type NodeState = "idle" | "running" | "completed" | "skipped" | "failed" | "manual";
export type GraphStates = Record<"intake" | "privacy" | "routing" | "reviewer", NodeState>;
export type HandoffPulse = { key:number; edge:"intake-privacy"|"intake-routing"|"privacy-routing"|"routing-reviewer"; direction:"forward"|"reverse" } | null;

export function WorkflowGraph({states,selected,pulse,manual}:{states:GraphStates;selected:Department|null;pulse:HandoffPulse;manual:boolean}) {
  return <section className="min-w-0 overflow-hidden rounded-3xl border border-slate-200 bg-white p-5 sm:p-6 card-shadow">
    <div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-400">Live workflow</p><h2 className="mt-1 text-lg font-semibold text-slate-950">Real backend transitions</h2></div><span className="shrink-0 rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-500">No staged timers</span></div>
    <div className="mt-7 grid grid-cols-[minmax(0,1fr)_32px_minmax(0,1fr)_32px_minmax(0,1.2fr)_32px_minmax(0,1fr)] items-center gap-0">
      <Node label="Intake" state={states.intake}/><Edge active={states.privacy!=="idle"} pulse={pulse?.edge==="intake-privacy"?pulse:null}/><Node label="Privacy" state={states.privacy}/><Edge active={states.routing!=="idle"} pulse={pulse?.edge==="privacy-routing"||pulse?.edge==="intake-routing"?pulse:null}/><div className="min-w-0"><Node label="Routing" state={states.routing}/><div className="mt-2 flex flex-wrap justify-center gap-1.5">{(["technical","business","finance"] as const).map(d=><span key={d} className={`rounded-full border px-2 py-1 text-[10px] font-bold capitalize ${selected===d?"border-[var(--pegas-blue)] bg-[var(--pegas-blue-soft)] text-[var(--pegas-blue-dark)]":"border-slate-200 bg-slate-50 text-slate-400"}`}>{d}</span>)}</div></div><Edge active={states.reviewer!=="idle"} pulse={pulse?.edge==="routing-reviewer"?pulse:null}/><Node label="Reviewer" state={manual&&states.reviewer==="idle"?"manual":states.reviewer}/>
    </div>
  </section>;
}
function Node({label,state}:{label:string;state:NodeState}) { const c:Record<NodeState,string>={idle:"border-slate-200 bg-slate-50 text-slate-500",running:"border-[var(--pegas-blue)] bg-[var(--pegas-blue-soft)] text-[var(--pegas-blue-dark)] shadow-[0_0_0_4px_rgba(63,94,251,0.08)]",completed:"border-emerald-200 bg-emerald-50 text-emerald-800",skipped:"border-slate-200 bg-slate-50 text-slate-300",failed:"border-rose-200 bg-rose-50 text-rose-700",manual:"border-amber-200 bg-amber-50 text-amber-800"}; const sl=state==="skipped"&&label==="Privacy"?"not needed":state; return <div className={`min-w-0 rounded-2xl border px-2 py-5 text-center text-xs font-semibold transition sm:px-3 sm:text-sm ${c[state]}`}><span className="block truncate">{label}</span><span className="mt-1 block truncate text-[9px] font-bold uppercase tracking-wider opacity-70 sm:text-[10px] sm:tracking-widest">{sl}</span></div> }
function Edge({active,pulse}:{active:boolean;pulse:HandoffPulse}) { return <div className="relative mx-1 h-1 rounded-full bg-slate-200"><div className={`absolute inset-0 rounded-full transition ${active?"pegas-gradient-fill":"bg-transparent"}`}/>{active&&pulse&&<span key={pulse.key} className={`${pulse.direction==="reverse"?"handoff-pulse-reverse":"handoff-pulse"} absolute left-0 top-1/2 h-3 w-3 -translate-y-1/2 rounded-full bg-[var(--pegas-cyan)] shadow-[0_0_18px_rgba(24,208,255,0.8)]`}/>}</div> }
