type SmokeEvent={type:string;payload?:{agentic_payment_evidence?:{authority?:unknown;policy?:unknown;identity?:unknown;settlement?:{transaction_signature?:unknown;transfer_matches_offer?:unknown};};legal_consultation?:unknown}};
const GATE="YES_I_ACCEPT_ONE_DEVNET_TEST_PAYMENT";
if(process.env.LIVE_X402_SMOKE_CONFIRM!==GATE){console.error(`LIVE SMOKE NOT RUN. Set LIVE_X402_SMOKE_CONFIRM=${GATE} only after configuring/funding the dedicated Devnet wallets, RPC, Redis and facilitator.`);process.exit(2);}
const base=process.env.LEGAL_SERVICE_BASE_URL?.replace(/\/$/,"");if(!base)throw new Error("LEGAL_SERVICE_BASE_URL is required");
const clientRequestId=crypto.randomUUID();const message="Please review a vendor NDA before signature. It lets the vendor use our confidential information to train its AI models and does not specify when shared information must be deleted or returned. Should our Legal team review these terms?";
async function run(cookie?:string){const response=await fetch(`${base}/api/workflows/run`,{method:"POST",headers:{"Content-Type":"application/json",...(cookie?{Cookie:cookie}:{})},body:JSON.stringify({message,scenario:"paid_legal",client_request_id:clientRequestId}),redirect:"error"});const setCookie=response.headers.get("set-cookie");if(!response.ok){console.error(await response.text());throw new Error(`workflow HTTP ${response.status}`)}const text=await response.text();const events=text.split("\n\n").map(frame=>frame.split("\n").find(x=>x.startsWith("data: "))).filter(Boolean).map(line=>JSON.parse(line!.slice(6)) as SmokeEvent);return{events,cookie:setCookie?.split(";",1)[0]??cookie};}
const first=await run();const authorized=first.events.filter(e=>e.type==="payment_authorized");const confirmed=first.events.find(e=>e.type==="payment_confirmed");const consumed=first.events.find(e=>e.type==="mandate_consumed");const completed=first.events.find(e=>e.type==="workflow_completed");if(authorized.length!==1||!confirmed||!consumed||!completed)throw new Error("Live smoke did not prove the complete single-payment flow");const evidence=completed.payload?.agentic_payment_evidence;if(!evidence?.settlement?.transaction_signature||evidence?.settlement?.transfer_matches_offer!==true)throw new Error("Live smoke lacks matching chain evidence");console.log(JSON.stringify({mandate:evidence.authority,policy:evidence.policy,identity:evidence.identity,settlement:evidence.settlement,legal:completed.payload?.legal_consultation??null},null,2));
const duplicate=await run(first.cookie);const duplicateAuthorized=duplicate.events.filter(e=>e.type==="payment_authorized");if(duplicateAuthorized.length!==0)throw new Error("Duplicate request attempted a second authorization");console.log("Duplicate replay/recheck produced no second payment authorization. Consumed mandate cannot authorize again.");

export {};
