import { isSolanaPublicKey } from "../lib/payments/solana-utils.ts";
const NETWORK="solana:EtWTRABZaYq6iMfeYKouRu166VU2xqa1";
const GENESIS="EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG";
const MINT="4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU";
const env=(name:string)=>process.env[name]?.trim()??"";
const config={enabled:env("AGENTIC_PAYMENTS_ENABLED")==="true",facilitator:env("X402_FACILITATOR_URL")||"https://x402.org/facilitator",network:env("SOLANA_NETWORK")||NETWORK,mint:env("SOLANA_USDC_MINT")||MINT,rpc:env("SOLANA_RPC_URL"),secret:env("PAYMENT_BUYER_PRIVATE_KEY"),buyer:env("PAYMENT_BUYER_ADDRESS"),seller:env("LEGAL_PAY_TO"),service:env("LEGAL_SERVICE_BASE_URL"),auth:env("LEGAL_SERVICE_AUTH_SECRET"),amount:env("LEGAL_CONSULTATION_AMOUNT_ATOMIC")||"10000",maxOp:env("PAYMENT_MAX_PER_OPERATION_ATOMIC")||"10000",redis:env("UPSTASH_REDIS_REST_URL"),redisToken:env("UPSTASH_REDIS_REST_TOKEN")};
type RpcEnvelope<T>={result?:T;error?:unknown};
type Support={x402Version?:unknown;scheme?:unknown;network?:unknown;feePayer?:unknown;extra?:{feePayer?:unknown}};
type TokenAccountEntry={
  account?:{
    data?:{
      parsed?:{
        info?:{
          tokenAmount?:{amount?:string|number|bigint|boolean};
        };
      };
    };
  };
};
type TokenAccountsResult={value?:TokenAccountEntry[]};
function decodeBase58(input:string){const alphabet="123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";const bytes=[0];for(const ch of input){const value=alphabet.indexOf(ch);if(value<0)throw new Error("invalid base58 private key");let carry=value;for(let j=0;j<bytes.length;j++){carry+=bytes[j]*58;bytes[j]=carry&255;carry>>=8}while(carry){bytes.push(carry&255);carry>>=8}}for(let i=0;i<input.length-1&&input[i]==="1";i++)bytes.push(0);return Uint8Array.from(bytes.reverse())}
async function rpc<T=unknown>(method:string,params:unknown[]):Promise<T>{const r=await fetch(config.rpc,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:1,method,params}),redirect:"error"});if(!r.ok)throw new Error(`${method}: HTTP ${r.status}`);const j=await r.json() as RpcEnvelope<T>;if(j.error)throw new Error(`${method}: RPC error`);return j.result as T}
function findSupport(v:unknown):Support|null{if(Array.isArray(v)){for(const x of v){const f=findSupport(x);if(f)return f}return null}if(!v||typeof v!=="object")return null;const obj=v as Record<string,unknown>;if(obj.x402Version===2&&obj.scheme==="exact"&&obj.network===NETWORK)return obj as Support;for(const x of Object.values(obj)){const f=findSupport(x);if(f)return f}return null}
async function main(){console.log("Pegas Agentic Payments setup check (no spend)");const required:[[string,string],...[string,string][]]=[["SOLANA_RPC_URL",config.rpc],["PAYMENT_BUYER_PRIVATE_KEY",config.secret],["PAYMENT_BUYER_ADDRESS",config.buyer],["LEGAL_PAY_TO",config.seller],["LEGAL_SERVICE_BASE_URL",config.service],["LEGAL_SERVICE_AUTH_SECRET",config.auth],["UPSTASH_REDIS_REST_URL",config.redis],["UPSTASH_REDIS_REST_TOKEN",config.redisToken]];let failed=false;if(!config.enabled){console.log("FAIL config: AGENTIC_PAYMENTS_ENABLED is not true");failed=true}if(config.network!==NETWORK){console.log("FAIL config: SOLANA_NETWORK mismatch");failed=true}if(config.mint!==MINT){console.log("FAIL config: SOLANA_USDC_MINT mismatch");failed=true}if(config.amount!=="10000"||config.maxOp!=="10000"){console.log("FAIL config: fixed amount/per-operation ceiling must equal 10000");failed=true}for(const[name,value]of required)if(!value){console.log(`FAIL config: ${name} is required`);failed=true}if(config.buyer&&config.buyer===config.seller){console.log("FAIL config: buyer and seller must differ");failed=true}if(config.buyer&&!isSolanaPublicKey(config.buyer)){console.log("FAIL config: PAYMENT_BUYER_ADDRESS is not a valid Solana public key");failed=true}if(config.seller&&!isSolanaPublicKey(config.seller)){console.log("FAIL config: LEGAL_PAY_TO is not a valid Solana public key");failed=true}if(failed){process.exitCode=1;return}
 try{const r=await fetch(config.redis,{method:"POST",headers:{Authorization:`Bearer ${config.redisToken}`,"Content-Type":"application/json"},body:JSON.stringify(["PING"]),redirect:"error"});const j=await r.json() as {result?:unknown};console.log(`Redis connectivity: ${r.ok&&j.result==="PONG"?"PASS":"FAIL"}`);if(!(r.ok&&j.result==="PONG"))failed=true}catch(e){console.log(`Redis connectivity: FAIL (${e instanceof Error?e.message:"error"})`);failed=true}
 try{const kit=await import("@solana/kit");const secret=decodeBase58(config.secret);const signer=await kit.createKeyPairSignerFromBytes(secret);const match=String(signer.address)===config.buyer;console.log(`Buyer secret/public key match: ${match?"PASS":"FAIL"}`);if(!match)failed=true}catch(e){console.log(`Buyer secret/public key match: FAIL (${e instanceof Error?e.message:"SDK/key error"})`);failed=true}
 console.log(`Agent Registry buyer binding: ${config.buyer?"PASS":"FAIL"}`);console.log(`Agent Registry Legal Advisor binding: ${config.seller?"PASS":"FAIL"}`);
 try{const genesis=await rpc<string>("getGenesisHash",[]);const ok=genesis===GENESIS;console.log(`Solana RPC Devnet genesis: ${ok?"PASS":"FAIL"}`);if(!ok)failed=true}catch(e){console.log(`Solana RPC Devnet genesis: FAIL (${e instanceof Error?e.message:"error"})`);failed=true}
 try{const mint=await rpc<{value?:{data?:{parsed?:{info?:{decimals?:unknown}}}}}>("getAccountInfo",[config.mint,{encoding:"jsonParsed",commitment:"confirmed"}]);const decimals=mint?.value?.data?.parsed?.info?.decimals;const ok=decimals===6;console.log(`Devnet USDC mint / 6 decimals: ${ok?"PASS":"FAIL"}`);if(!ok)failed=true}catch(e){console.log(`Devnet USDC mint: FAIL (${e instanceof Error?e.message:"error"})`);failed=true}
 try{const balances=await rpc<TokenAccountsResult>("getTokenAccountsByOwner",[config.buyer,{mint:config.mint},{encoding:"jsonParsed",commitment:"confirmed"}]);const values=Array.isArray(balances?.value)?balances.value:[];const total=values.reduce((sum:bigint,v)=>sum+BigInt(v?.account?.data?.parsed?.info?.tokenAmount?.amount??"0"),0n);const enough=total>=10000n;console.log(`Buyer test USDC balance >= 10000 atomic: ${enough?"PASS":"FAIL"} (${total} atomic)`);if(!enough)failed=true}catch(e){console.log(`Buyer test USDC balance readable: FAIL (${e instanceof Error?e.message:"error"})`);failed=true}
 try{const r=await fetch(`${config.facilitator.replace(/\/$/,"")}/supported`,{headers:{Accept:"application/json"},redirect:"error"});const data=await r.json();const support=findSupport(data);const feePayer=support?.extra?.feePayer??support?.feePayer;const ok=r.ok&&typeof feePayer==="string"&&isSolanaPublicKey(feePayer);console.log(`Facilitator V2 exact Devnet + valid fee payer: ${ok?"PASS":"FAIL"}`);if(!ok)failed=true}catch(e){console.log(`Facilitator V2 exact Devnet: FAIL (${e instanceof Error?e.message:"error"})`);failed=true}
 try{const u=new URL(config.service);const allowed=u.protocol==="https:"||(process.env.NODE_ENV!=="production"&&(u.hostname==="localhost"||u.hostname==="127.0.0.1"));console.log(`Internal Legal service URL: ${allowed?"PASS":"FAIL"}`);if(!allowed)failed=true}catch{console.log("Internal Legal service URL: FAIL");failed=true}
 console.log("No signing or settlement was attempted. Secrets and credential-bearing URLs are not printed.");if(failed)process.exitCode=1}
main().catch(e=>{console.error("Setup check failed safely:",e instanceof Error?e.message:"unknown error");process.exitCode=1});
export {};
