import assert from "node:assert/strict";
import { DEPARTMENT_PROFILES } from "../lib/workflow/departments.ts";
import { buildPrivacyRoutingContext } from "../lib/workflow/privacy.ts";
import { decideReviewPath } from "../lib/workflow/correction.ts";
import type { IntakeAssessment, PrivacyDecision, ReviewDecision, RoutingDecision } from "../lib/workflow/types";
assert.deepEqual(DEPARTMENT_PROFILES.map(x=>x.id),["technical","business","finance"]);
assert.equal(DEPARTMENT_PROFILES.some(x=>"agent_id" in x),false);
const intake:IntakeAssessment={summary:"s",request_type:"partnership",department_candidate:"business",priority:"medium",confidentiality:"confidential",privacy_review_needed:true,route_reason:"r",evidence:[],missing_information:[],clarification_question:null};
const privacy:PrivacyDecision={decision:"continue",confidentiality:"confidential",safe_brief:"safe commercial brief",reason:"reduce",recipient_restrictions:["minimum only"],withheld_field_names:["sanitized_request"],evidence:[],clarification_question:null};
const normal={sanitized_request:"fictional request",intake,department_profiles:DEPARTMENT_PROFILES}; assert.equal("sanitized_request" in normal,true);
const reduced=buildPrivacyRoutingContext({privacy,intake}); assert.equal("sanitized_request" in reduced,false);
const correction={...reduced,previous_routing_decision:{department:"business"},reviewer_issues:["issue"],correction_cycle:1}; assert.equal("sanitized_request" in correction,false);
const routing:RoutingDecision={department:"business",summary:"s",priority:"medium",confidentiality:"internal",routing_reason:"r",department_brief:"b",next_action:"n",open_questions:[],evidence:[]};
const review:ReviewDecision={decision:"revise",issues:["billing owns this"],correction_target:"finance",correction_request:"Re-evaluate",reason:"Wrong owner",evidence:[]};
const first=decideReviewPath({review,currentDepartment:"business",routing,correctionCycleUsed:false}); assert.equal(first.action,"revise");
const second=decideReviewPath({review,currentDepartment:"finance",routing:{...routing,department:"finance"},correctionCycleUsed:true}); assert.equal(second.action,"manual_review");
const routing2={...routing,department:"technical" as const}; assert.equal(routing2.department,"technical","final reroute comes from Routing #2 output, not reviewer suggestion");
const restricted=decideReviewPath({review:{...review,decision:"approved",correction_target:null,reason:"Approved"},currentDepartment:"business",routing:{...routing,confidentiality:"restricted"},correctionCycleUsed:false,privacyCleared:true}); assert.equal(restricted.action,"manual_review");
console.log("Phase 4 routing tests passed.");
