import type { AgentMandate, MandateControlResult, MandatePolicyDecision, X402PaymentRequirement } from "./types";
import type { PaymentConfig } from "./config";
import type { AgentRegistryEntry } from "./types";

export function evaluateMandatePolicy(args:{config:PaymentConfig;mandate:AgentMandate;buyer:AgentRegistryEntry|null;seller:AgentRegistryEntry|null;quote:X402PaymentRequirement;resourceUrl:string;expectedResourceUrl:string;recipientRestrictions:string[];authorizationCount:number;remainingMs:number;budgetAvailable:boolean;now?:number}):MandatePolicyDecision{
 const {config,mandate,seller,quote}=args;const now=args.now??Date.now();const results:MandateControlResult[]=[];const add=(id:MandateControlResult["id"],label:string,passed:boolean,reason:string)=>results.push({id,label,passed,public_reason:reason});
 add("AUTH-01","Feature and mandate state",config.enabled&&mandate.state==="active",config.enabled&&mandate.state==="active"?"Payment feature is enabled and the operation mandate is active.":"Payment feature is disabled or the mandate is not active.");
 add("AUTH-02","Expiry and deadline reserve",Date.parse(mandate.expires_at)>now&&args.remainingMs>=25_000,Date.parse(mandate.expires_at)>now&&args.remainingMs>=25_000?"Mandate is unexpired and enough workflow time remains for settlement evidence.":"Mandate expired or insufficient time remains to settle and verify safely.");
 add("AUTH-03","Service scope",mandate.service_id==="legal_consultation",mandate.service_id==="legal_consultation"?"Mandate is scoped to legal_consultation only.":"Requested service is outside mandate scope.");
 const cp=Boolean(seller&&seller.status==="registered"&&seller.agent_id===mandate.counterparty_agent_id&&seller.payment_address===mandate.allowed_payee&&quote.payTo===seller.payment_address); add("AUTH-04","Registered counterparty",cp,cp?"Legal Advisor is registered and the quoted seller wallet matches its bound demo identity.":"Counterparty identity or seller wallet binding does not match.");
 add("AUTH-05","Network allowlist",quote.network===config.network&&mandate.network===config.network,quote.network===config.network&&mandate.network===config.network?"Quote and mandate are restricted to Solana Devnet.":"Quote requests a network outside the mandate.");
 add("AUTH-06","Asset allowlist",quote.asset===config.assetMint&&mandate.asset_mint===config.assetMint,quote.asset===config.assetMint&&mandate.asset_mint===config.assetMint?"Quote uses the configured Devnet test USDC mint.":"Quote requests an asset outside the mandate.");
 const amountOk=quote.amount==="10000"&&BigInt(quote.amount)<=BigInt(mandate.max_amount_atomic)&&quote.amount===config.amountAtomic;add("AUTH-07","Amount ceiling",amountOk,amountOk?"Quote is exactly 10000 atomic (0.01 test USDC) and within the mandate ceiling.":"Quote amount is not the fixed authorized amount or exceeds the mandate ceiling.");
 const one=args.authorizationCount===0&&mandate.max_authorizations===1;add("AUTH-08","Single authorization",one,one?"No prior authorization exists and the mandate permits exactly one.":"The one-authorization limit is already reserved or invalid.");
 const restrictionsOk=!args.recipientRestrictions.some(r=>/no external|do not forward|manual|restricted/i.test(r)); const resourceOk=args.resourceUrl===args.expectedResourceUrl; add("AUTH-09","Request and privacy binding",resourceOk&&restrictionsOk,resourceOk&&restrictionsOk?"The quote is bound to the configured resource and recipient restrictions permit the specialist handoff.":"Resource binding or recipient/privacy restrictions block payment.");
 add("AUTH-10","Budget and rate controls",args.budgetAvailable,args.budgetAvailable?"Atomic budget/rate reservation is available for this fixed charge.":"Session/daily budget or rate controls decline the charge.");
 return {mandate_id:mandate.mandate_id,decision:results.every(r=>r.passed)?"approved":"declined",checked_at:new Date(now).toISOString(),controls:results};
}
