import { createHash } from "node:crypto";
import type { PaymentConfig } from "./config";
import type { PaymentRequired, SettleResponse } from "@x402/core/types";
import type { X402PaymentRequired, X402PaymentRequirement } from "./types";
import { isSolanaPublicKey } from "./solana-utils.ts";

let supportCache:{expires:number;feePayer:string}|null=null;
function timeoutSignal(ms:number){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);return {signal:c.signal,done:()=>clearTimeout(t)};}
async function httpCodec(){const {x402HttpCodec}=await import("./x402-http-codec.ts");return x402HttpCodec;}
function isCaip2Network(value:string):value is `${string}:${string}`{const separator=value.indexOf(":");return separator>0&&separator<value.length-1;}
function assertOfficialPaymentRequired(required:X402PaymentRequired):asserts required is X402PaymentRequired&PaymentRequired{if(!required.accepts.every(option=>isCaip2Network(option.network)))throw new Error("x402 payment requirement network must be CAIP-2");}
export async function encodePaymentRequiredHeader(value:X402PaymentRequired){assertOfficialPaymentRequired(value);return (await httpCodec()).encodePaymentRequiredHeader(value) as string;}
export async function decodePaymentRequiredHeader(value:string){return (await httpCodec()).decodePaymentRequiredHeader(value) as X402PaymentRequired;}
export async function decodePaymentSignatureHeader(value:string){return (await httpCodec()).decodePaymentSignatureHeader(value) as unknown;}
export async function encodePaymentResponseHeader(value:SettleResponse){return (await httpCodec()).encodePaymentResponseHeader(value) as string;}
export function quoteFingerprint(required:X402PaymentRequired){return createHash("sha256").update(JSON.stringify(required)).digest("hex");}
export function freezePaymentRequired(required:X402PaymentRequired):X402PaymentRequired{const copy=structuredClone(required);const freeze=(v:unknown):unknown=>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){for(const child of Object.values(v))freeze(child);Object.freeze(v)}return v};return freeze(copy) as X402PaymentRequired;}

function findSupportedKind(value:unknown,network:string):Record<string,unknown>|null{if(Array.isArray(value)){for(const item of value){const found=findSupportedKind(item,network);if(found)return found;}return null;}if(!value||typeof value!=="object")return null;const obj=value as Record<string,unknown>;if(obj.x402Version===2&&obj.scheme==="exact"&&obj.network===network)return obj;for(const v of Object.values(obj)){const found=findSupportedKind(v,network);if(found)return found;}return null;}
export function isValidFacilitatorFeePayer(value:unknown):value is string{return typeof value==="string"&&isSolanaPublicKey(value);}
export async function getFacilitatorSupport(config:PaymentConfig,remainingMs=5000){if(supportCache&&supportCache.expires>Date.now())return {supported:true as const,feePayer:supportCache.feePayer};const timer=timeoutSignal(Math.max(1,Math.min(5000,remainingMs)));try{const res=await fetch(`${config.facilitatorUrl.replace(/\/$/,"")}/supported`,{headers:{Accept:"application/json"},signal:timer.signal,cache:"no-store",redirect:"error"});if(!res.ok)return {supported:false as const,reason:`facilitator_supported_http_${res.status}`};const data=await res.json();const kind=findSupportedKind(data,config.network);const extra=(kind?.extra&&typeof kind.extra==="object"?kind.extra:{}) as Record<string,unknown>;const feePayer=typeof extra.feePayer==="string"?extra.feePayer:typeof kind?.feePayer==="string"?kind.feePayer:null;if(!kind||!isValidFacilitatorFeePayer(feePayer))return {supported:false as const,reason:"facilitator_does_not_advertise_valid_x402_v2_exact_devnet_fee_payer"};supportCache={expires:Date.now()+60_000,feePayer};return {supported:true as const,feePayer};}catch(error){return {supported:false as const,reason:error instanceof Error?error.message:"facilitator_support_failed"};}finally{timer.done();}}
export function buildLegalPaymentRequired(args:{config:PaymentConfig;resourceUrl:string;feePayer:string;operationId:string}):X402PaymentRequired&PaymentRequired{const requirement:X402PaymentRequirement={scheme:"exact",network:args.config.network,amount:"10000",asset:args.config.assetMint,payTo:args.config.legalPayTo,maxTimeoutSeconds:60,extra:{feePayer:args.feePayer,paymentFlow:"upfront",memo:`pegas:${args.operationId.slice(0,40)}`}};const required:X402PaymentRequired={x402Version:2,error:"PAYMENT-SIGNATURE header is required",resource:{url:args.resourceUrl,description:"Pegas Legal Advisor demo consultation",mimeType:"application/json",serviceName:"Pegas Legal Advisor"},accepts:[requirement],extensions:{}};assertOfficialPaymentRequired(required);return required;}
export function requireFrozenOffer(required:X402PaymentRequired,config:PaymentConfig,resourceUrl:string){const q=required.accepts[0];return Boolean(required.x402Version===2&&required.accepts.length===1&&q?.scheme==="exact"&&q.network===config.network&&q.asset===config.assetMint&&q.amount==="10000"&&q.payTo===config.legalPayTo&&q.extra?.paymentFlow==="upfront"&&required.resource.url===resourceUrl);}
export async function settleThroughFacilitator(args:{config:PaymentConfig;paymentPayload:unknown;requirement:X402PaymentRequirement;remainingMs:number}){const ms=Math.max(1,Math.min(20_000,args.remainingMs));const timer=timeoutSignal(ms);let submitted=false;try{submitted=true;const res=await fetch(`${args.config.facilitatorUrl.replace(/\/$/,"")}/settle`,{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({x402Version:2,paymentPayload:args.paymentPayload,paymentRequirements:args.requirement}),signal:timer.signal,cache:"no-store",redirect:"error"});const body=await res.json().catch(()=>null) as Record<string,unknown>|null;if(!res.ok)return {kind:"rejected" as const,status:res.status,body};const success=body?.success===true;const transaction=typeof body?.transaction==="string"?body.transaction:null;const payer=typeof body?.payer==="string"?body.payer:null;if(!success||!transaction)return {kind:"rejected" as const,status:res.status,body};return {kind:"settled" as const,transaction,payer,body};}catch(error){return submitted?{kind:"unknown" as const,error:error instanceof Error?error.message:"settlement_transport_error"}:{kind:"failed" as const,error:"not_submitted"};}finally{timer.done();}}
